catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.index, name='index'),
   path('students/', views.StudentListView.as_view(), name='students'),
   path('student/<int:pk>', views.StudentDetailView.as_view(), name='student-detail'),
  

]

fakonn/locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

fakonn/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.conf.urls import include

# Use include() to add paths from the catalog application 
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.contrib.auth.models import User

class Institut(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    name = models.CharField(max_length=200, help_text="engiz")
    
    
    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name

from django.urls import reverse #Used to generate URLs by reversing the URL patterns

class Student(models.Model):
    """
    Model representing a student (but not a specific copy of a book).
    """
    
    title = models.CharField(max_length=200)
   
    kafedra = models.ForeignKey('Kafedra', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file.
    summary = models.TextField(max_length=1000, help_text='engiz')
    isbn = models.CharField('ISBN',max_length=15, help_text='15 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    institut = models.ManyToManyField(Institut, help_text='Select ')
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    
   
    def display_institut(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([ institut.name for institut in self.institut.all()[:3] ])
	
    display_institut.short_description = 'Institut'
    
    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.university_name
		
    def get_absolute_url(self):
        """
        Returns the url to access a detail record for .
        """
        return reverse('student-detail', args=[str(self.id)])

import uuid # Required for unique book instances

class StudentInstance(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    student = models.ForeignKey('Student', on_delete=models.SET_NULL, null=True) 
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'IITT'),
        ('o', 'KHTOF'),
        ('a', 'AS'),
        ('r', 'POU'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Student availability')

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)
        

    def __str__(self):
        """
        String for representing the Model object
        """
        return '{0} ({1})'.format(self.id,self.student.title)
class Kafedra(models.Model):
    """
    Model representing .
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    
    

    class Meta:
        ordering = ["last_name","first_name"]
    
    def get_absolute_url(self):
        """
        Returns 
        """
        return reverse('kafedra-detail', args=[str(self.id)])
    

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '{0}, {1}'.format(self.last_name,self.first_name)
   

catalog/views.py
from django.shortcuts import render

# Create your views here.

from .models import Student, Kafedra, StudentInstance, Institut

def index(request):
    """
  
    """
   
    num_students=Student.objects.all().count()
    num_instances=StudentInstance.objects.all().count()
    
    num_instances_available=StudentInstance.objects.filter(status__exact='a').count()
    num_kafedras=Kafedra.objects.count()  

     # Number of visits to this view, as counted in the session variable.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1
    
    return render(
        request,
        'index.html',
      context={'num_students':num_students,'num_instances':num_instances,'num_instances_available':num_instances_available,'num_kafedras':num_kafedras,
            'num_visits':num_visits}, # num_visits appended
    )

from django.views import generic

class StudentListView(generic.ListView):
    model = Student
    paginate_by = 2
class StudentDetailView(generic.DetailView):
    model = Student

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'books' %}">All students</a></li>
          <li><a href="{% url 'authors' %}">All kafedras</a></li>
          {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
   {% else %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
   {% endif %} 
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      {% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>KAFEDRA: {{ kafedra.first_name }}, {{ kafedra.last_name }} </h1>
  </n>{{kafedra.date_of_birth}}
  <div style="margin-left:20px;margin-top:20px">
  <p><strong>STUDENTS:</strong> {{ student.title }}</p>
  <p><strong>last_name:</strong> <a href="">{{ kafedra.last_name }}</a></p>
  <p><strong>first_name:</strong> <a href="">{{ kafedra.first_name }}</a></p> <!--  -->
  <p><strong>date_of_birth:</strong> {{ kafedra.date_of_birth }}</p> 
  <p><strong>date_of_death:</strong> {{ kafedra.date_of_death }}</p>  
  </div>
{% endblock %}

catalog/templates/catalog/kafedra_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>KAFEDRA: {{ kafedra.first_name }}, {{ kafedra.last_name }} </h1>
  </n>{{kafedra.date_of_birth}}
  <div style="margin-left:20px;margin-top:20px">
  <p><strong>BOOKS:</strong> {{ student.title }}</p>
  <p><strong>last_name:</strong> <a href="">{{ kafedra.last_name }}</a></p>
  <p><strong>first_name:</strong> <a href="">{{ kafedra.first_name }}</a></p> <!--  -->
  <p><strong>date_of_birth:</strong> {{ kafedra.date_of_birth }}</p> 
  <p><strong>date_of_death:</strong> {{ kafedra.date_of_death }}</p>  
  </div>
{% endblock %}

catalog/templates/catalog/kafedra_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Kafedra List</h1>

    {% if kafedra_list %}
    <ul>

      {% for kafedra in kafedra_list %}
      <li>
        <a href="{{ kafedra.get_absolute_url }}">{{kafedra.first_name}},{{kafedra.last_name}}({{kafedra.date_of_birth}})</a> ({{kafedra.date_of_death}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p></p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/student_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Kafedra:</strong> <a href="{% url 'kafedra-detail' book.kafedra.pk %}">{{ student.kafedra }}</a></p><!--  -->
  <p><strong>Summary:</strong> {{ student.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ student.language }}</p>  
  <p><strong>Institut:</strong> {% for institut in student.institut.all %} {{ institut }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in student.studentinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/student_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Student List</h1>

    {% if student_list %}
    <ul>

      {% for student in student_list %}
      <li>
        <a href="{{ student.get_absolute_url }}">{{ student.title }}</a> ({{student.kafedra}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      
    {% endif %}       
{% endblock %}

catalog/templates/catalog/student_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Renew: {{studentinst.student.title}}</h1>
    <p>Borrower: {{studentinst.borrower}}</p>
    <p{% if studentinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{studentinst.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

catalog/templates/catalog/studentinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Student</h1>

    {% if studentinstance_list %}
    <ul>

      {% for studentinst in studentinstance_list %} 
      <li class="{% if studentinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'student-detail' studentinst.student.pk %}">{{studentinst.student.title}}</a> ({{ studentinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
    
    {% endif %}       
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Local Home</h1>

  <p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>

<h2>Dynamic content</h2>

<p>The library has the following record counts:</p>
<ul>
<li><strong>Students:</strong> {{ num_students }}</li>
<li><strong>Copies:</strong> {{ num_instances }}</li>
<li><strong>Copies available:</strong> {{ num_instances_available }}</li>
<li><strong>Kafedras:</strong> {{ num_kafedras }}</li>
</ul>

<p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

{% endblock %}